name: TradeShop-Test
version: 0.0.1
main: org.shanerx.tradeshoptest.TradeShopTest
api-version: 1.14
load: POSTWORLD
depend: [TradeShop]

authors: [Lori00, KillerOfPie]
description: A new powerful trading plugin.
website: https://www.tradeshop.github.io

commands:
  tradeshoptest:
    description: Core command for TradeShop-Test
    aliases: [tst]
