name: ${project.name}
version: ${project.version}
main: org.shanerx.tradeshoptest.TradeShopTest
api-version: 1.14
load: POSTWORLD
depend: [ TradeShop ]

authors: [ Lori00, KillerOfPie ]
description: ${project.description}
website: ${project.url}

commands:
  tradeshoptest:
    description: Core command for TradeShop-Test
    aliases: [ tst ]
