name: TradeShop-Test
version: ${project.version}
main: org.shanerx.tradeshoptest.TradeShopTest
api-version: 1.14
load: POSTWORLD
depend: [ TradeShop ]

authors: [ Lori00, KillerOfPie ]
description: Test/Reference Add-On Plugin for TradeShop.
website: www.tradeshop.github.io

commands:
  tradeshoptest:
    description: Core command for TradeShop-Test
    aliases: [ tst ]
